version: "3.8"

services:

  # =====================
  # AIRFLOW METADATA DB
  # =====================
  postgres_airflow:
    image: postgres:14
    container_name: postgres_airflow
    env_file: .env
    environment:
      POSTGRES_DB: ${AIRFLOW_DB}
      POSTGRES_USER: ${AIRFLOW_DB_USER}
      POSTGRES_PASSWORD: ${AIRFLOW_DB_PASSWORD}
    volumes:
      - postgres_airflow_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      retries: 5

  # =====================
  # POSTGRES SOURCE DB
  # =====================
  postgres_source:
    image: postgres:14
    container_name: postgres_source
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - ./init-db/postgres:/docker-entrypoint-initdb.d

  # =====================
  # MYSQL WAREHOUSE DB
  # =====================
  mysql_warehouse:
    image: mysql:8.0
    container_name: mysql_warehouse
    env_file: .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - ./init-db/mysql:/docker-entrypoint-initdb.d

  # =====================
  # AIRFLOW WEBSERVER
  # =====================
  airflow_webserver:
    image: apache/airflow:2.5.1
    container_name: airflow_webserver
    depends_on:
      postgres_airflow:
        condition: service_healthy
    env_file: .env
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    ports:
      - "8081:8080"
    command: >
      bash -c "
      airflow db upgrade &&
      airflow users create \
        --username airflow \
        --password airflow \
        --firstname Admin \
        --lastname User \
        --role Admin \
        --email admin@example.com || true &&
      airflow webserver
      "

  # =====================
  # AIRFLOW SCHEDULER
  # =====================
  airflow_scheduler:
    image: apache/airflow:2.5.1
    container_name: airflow_scheduler
    depends_on:
      postgres_airflow:
        condition: service_healthy
    env_file: .env
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    command: >
      bash -c "
      airflow db upgrade &&
      airflow scheduler
      "

volumes:
  postgres_airflow_data:
